// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5fr3dG3vRQCgufp_9Tj38MkCFBab9n_o',
    appId: '1:737645136618:web:d0a978893a31a37469a593',
    messagingSenderId: '737645136618',
    projectId: 'project-iq-fa13e',
    authDomain: 'project-iq-fa13e.firebaseapp.com',
    storageBucket: 'project-iq-fa13e.firebasestorage.app',
    measurementId: 'G-0TEY5133DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw-ExvwiUDFoNjuZXdV7drPEaiu48oy20',
    appId: '1:737645136618:android:b47c6c07c62a2b6e69a593',
    messagingSenderId: '737645136618',
    projectId: 'project-iq-fa13e',
    storageBucket: 'project-iq-fa13e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOR_0nS1Tn0uJAHM74lXzufYEWviYMNJs',
    appId: '1:737645136618:ios:684a0a552671387569a593',
    messagingSenderId: '737645136618',
    projectId: 'project-iq-fa13e',
    storageBucket: 'project-iq-fa13e.firebasestorage.app',
    iosBundleId: 'com.example.myprojectIq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOR_0nS1Tn0uJAHM74lXzufYEWviYMNJs',
    appId: '1:737645136618:ios:684a0a552671387569a593',
    messagingSenderId: '737645136618',
    projectId: 'project-iq-fa13e',
    storageBucket: 'project-iq-fa13e.firebasestorage.app',
    iosBundleId: 'com.example.myprojectIq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5fr3dG3vRQCgufp_9Tj38MkCFBab9n_o',
    appId: '1:737645136618:web:850b1e8ba26c3e6169a593',
    messagingSenderId: '737645136618',
    projectId: 'project-iq-fa13e',
    authDomain: 'project-iq-fa13e.firebaseapp.com',
    storageBucket: 'project-iq-fa13e.firebasestorage.app',
    measurementId: 'G-MVH3ECJ804',
  );
}
